### ISSUE TITLE
How to retrain the model and reproduce the result in the paper?

### ISSUE THREAD

**Issue by ccmCCMfk** [wmtlab/GrainGrasp#1]
Hello, thanks for your great work! I'm wondering how to reproduce the results in paper, eg.(Volume, depth, Displacement......), and I'm not sure about the example, I get different results compared with the results in paper when running the same run_complete.py program twice? What causes this?
![Screenshot from 2024-07-06 10-18-22](https://github.com/wmtlab/GrainGrasp/assets/86772637/f48bd12c-ab61-465d-b303-d8531cd59fd9)

**Comment by f-q23** [comment]
You can try replacing other objects to output, or try running run_only_opt.py, as your example shows that this seems to be caused by poor prediction results from the first stage model. You can also try visualizing all the outputs from the second stage to observe the results. As mentioned in our paper, our method is limited by the model output in the first stage.

For the volume and depth in the quantitative results, you can save the point cloud and mesh and use the Trimesh library to calculate them. For displacement, you need to install [v-hacd](https://github.com/kmammou/v-hacd), which we have referred to as [grasptta](https://github.com/hwjiang1510/GraspTTA/).

**Comment by fffffq00** [comment]
> Hello, thanks for your great work! I'm wondering how to reproduce the results in paper, eg.(Volume, depth, Displacement......), and I'm not sure about the example, I get different results compared with the results in paper when running the same run_complete.py program twice? What causes this? ![Screenshot from 2024-07-06 10-18-22](https://private-user-images.githubusercontent.com/86772637/346247056-f48bd12c-ab61-465d-b303-d8531cd59fd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTExOTQsIm5iZiI6MTcyMDI1MDg5NCwicGF0aCI6Ii84Njc3MjYzNy8zNDYyNDcwNTYtZjQ4YmQxMmMtYWI2MS00NjVkLWIzMDMtZDg1MzFjZDU5ZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA3MjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZDNmYTAxOWVkZmNmYjc2Mzg2NzEyN2NlZWVlZmU1MmNjOGUzMjkzNzBmOTFkYjRhNTFiZTExYWQ0YmRkMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6gThIcQuZyNiuN0G3Ul2U_xs8xEo5LNx-vu4gOdmXY)

You can try replacing other objects to output, or try running run_only_opt.py, as your example shows that this seems to be caused by poor prediction results from the first stage model. You can also try visualizing all the outputs from the second stage to observe the results. As mentioned in our paper, our method is limited by the model output in the first stage.

For the volume and depth in the quantitative results, you can save the point cloud and mesh and use the Trimesh library to calculate them. For displacement, you need to install [v-hacd](https://github.com/kmammou/v-hacd), which we have referred to as [grasptta](https://github.com/hwjiang1510/GraspTTA/).

**Comment by ccmCCMfk** [comment]
> > Hello, thanks for your great work! I'm wondering how to reproduce the results in paper, eg.(Volume, depth, Displacement......), and I'm not sure about the example, I get different results compared with the results in paper when running the same run_complete.py program twice? What causes this? ![Screenshot from 2024-07-06 10-18-22](https://private-user-images.githubusercontent.com/86772637/346247056-f48bd12c-ab61-465d-b303-d8531cd59fd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTExOTQsIm5iZiI6MTcyMDI1MDg5NCwicGF0aCI6Ii84Njc3MjYzNy8zNDYyNDcwNTYtZjQ4YmQxMmMtYWI2MS00NjVkLWIzMDMtZDg1MzFjZDU5ZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA3MjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZDNmYTAxOWVkZmNmYjc2Mzg2NzEyN2NlZWVlZmU1MmNjOGUzMjkzNzBmOTFkYjRhNTFiZTExYWQ0YmRkMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6gThIcQuZyNiuN0G3Ul2U_xs8xEo5LNx-vu4gOdmXY)
> 
> You can try replacing other objects to output, or try running run_only_opt.py, as your example shows that this seems to be caused by poor prediction results from the first stage model. You can also try visualizing all the outputs from the second stage to observe the results. As mentioned in our paper, our method is limited by the model output in the first stage.
> 
> For the volume and depth in the quantitative results, you can save the point cloud and mesh and use the Trimesh library to calculate them. For displacement, you need to install [v-hacd](https://github.com/kmammou/v-hacd), which we have referred to as [grasptta](https://github.com/hwjiang1510/GraspTTA/).

Thank you, I have tried to run_only_opt.py and run_complete.py，the results match the images in the article in most cases. and I'm sorry to bother you that can you open-source the testing program? Also, how to train the CVAE and DCOG models? Looking forward to your reply.

**Comment by fffffq00** [comment]
> > > Hello, thanks for your great work! I'm wondering how to reproduce the results in paper, eg.(Volume, depth, Displacement......), and I'm not sure about the example, I get different results compared with the results in paper when running the same run_complete.py program twice? What causes this? ![Screenshot from 2024-07-06 10-18-22](https://private-user-images.githubusercontent.com/86772637/346247056-f48bd12c-ab61-465d-b303-d8531cd59fd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTExOTQsIm5iZiI6MTcyMDI1MDg5NCwicGF0aCI6Ii84Njc3MjYzNy8zNDYyNDcwNTYtZjQ4YmQxMmMtYWI2MS00NjVkLWIzMDMtZDg1MzFjZDU5ZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA3MjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZDNmYTAxOWVkZmNmYjc2Mzg2NzEyN2NlZWVlZmU1MmNjOGUzMjkzNzBmOTFkYjRhNTFiZTExYWQ0YmRkMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6gThIcQuZyNiuN0G3Ul2U_xs8xEo5LNx-vu4gOdmXY)
> > 
> > 
> > You can try replacing other objects to output, or try running run_only_opt.py, as your example shows that this seems to be caused by poor prediction results from the first stage model. You can also try visualizing all the outputs from the second stage to observe the results. As mentioned in our paper, our method is limited by the model output in the first stage.
> > For the volume and depth in the quantitative results, you can save the point cloud and mesh and use the Trimesh library to calculate them. For displacement, you need to install [v-hacd](https://github.com/kmammou/v-hacd), which we have referred to as [grasptta](https://github.com/hwjiang1510/GraspTTA/).
> 
> Thank you, I have tried to run_only_opt.py and run_complete.py，the results match the images in the article in most cases. and I'm sorry to bother you that can you open-source the testing program? Also, how to train the CVAE and DCOG models? Looking forward to your reply.

In fact, in order to compare with other methods, I saved the hand and object meshes generated by various methods and then conducted quantitative experimental calculations, which caused me to be unable to organize this part of the code. However, these quantitative testing methods are all simple, and you can easily find relevant testing programs online.
The code for CVAE training is in [train](https://github.com/wmtlab/GrainGrasp/blob/main/PointCVAE/train.py). And DCoG is based on optimization methods, which do not require training, only need to adjust parameters. Some parameters can be adjusted in [config](https://github.com/wmtlab/GrainGrasp/blob/main/config.json). If you want to make more detailed adjustments, you may need to read the paper and code.
Thank you for your interest in our work. Due to my limited time, I cannot reply immediately. If you need any other assistance, such as encountering some problems in implementing the testing program or the testing program for perceptual study, please send me an email.

**Comment by ccmCCMfk** [comment]
> > > > Hello, thanks for your great work! I'm wondering how to reproduce the results in paper, eg.(Volume, depth, Displacement......), and I'm not sure about the example, I get different results compared with the results in paper when running the same run_complete.py program twice? What causes this? ![Screenshot from 2024-07-06 10-18-22](https://private-user-images.githubusercontent.com/86772637/346247056-f48bd12c-ab61-465d-b303-d8531cd59fd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTExOTQsIm5iZiI6MTcyMDI1MDg5NCwicGF0aCI6Ii84Njc3MjYzNy8zNDYyNDcwNTYtZjQ4YmQxMmMtYWI2MS00NjVkLWIzMDMtZDg1MzFjZDU5ZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA3MjgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZDNmYTAxOWVkZmNmYjc2Mzg2NzEyN2NlZWVlZmU1MmNjOGUzMjkzNzBmOTFkYjRhNTFiZTExYWQ0YmRkMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T6gThIcQuZyNiuN0G3Ul2U_xs8xEo5LNx-vu4gOdmXY)
> > > 
> > > 
> > > You can try replacing other objects to output, or try running run_only_opt.py, as your example shows that this seems to be caused by poor prediction results from the first stage model. You can also try visualizing all the outputs from the second stage to observe the results. As mentioned in our paper, our method is limited by the model output in the first stage.
> > > For the volume and depth in the quantitative results, you can save the point cloud and mesh and use the Trimesh library to calculate them. For displacement, you need to install [v-hacd](https://github.com/kmammou/v-hacd), which we have referred to as [grasptta](https://github.com/hwjiang1510/GraspTTA/).
> > 
> > 
> > Thank you, I have tried to run_only_opt.py and run_complete.py，the results match the images in the article in most cases. and I'm sorry to bother you that can you open-source the testing program? Also, how to train the CVAE and DCOG models? Looking forward to your reply.
> 
> In fact, in order to compare with other methods, I saved the hand and object meshes generated by various methods and then conducted quantitative experimental calculations, which caused me to be unable to organize this part of the code. However, these quantitative testing methods are all simple, and you can easily find relevant testing programs online. The code for CVAE training is in [train](https://github.com/wmtlab/GrainGrasp/blob/main/PointCVAE/train.py). And DCoG is based on optimization methods, which do not require training, only need to adjust parameters. Some parameters can be adjusted in [config](https://github.com/wmtlab/GrainGrasp/blob/main/config.json). If you want to make more detailed adjustments, you may need to read the paper and code. Thank you for your interest in our work. Due to my limited time, I cannot reply immediately. If you need any other assistance, such as encountering some problems in implementing the testing program or the testing program for perceptual study, please send me an email.

Thank you very much! I will first attempt to conduct the experiments on my own and send email for further communication.
