### ISSUE TITLE
Cannot generate good grasp poses for a new object. 

### ISSUE THREAD

**Issue by skymanaditya1** [wmtlab/GrainGrasp#3]
I am trying to evaluate grasp proposals on my own objects, but I always seem to get this error when running either the opt or complete model. 

-----------------DCoG Model loaded successfully-----------------
-----------------CVAE Model loaded successfully-----------------
The running time is 2.51s
The Epen is  (nan, nan, nan, nan, nan, nan)
The min_idx is  0

I tried visualizing my object along with the objects that you provide and there seems to be some translational difference between the two point clouds. 
![image](https://github.com/user-attachments/assets/c3384040-7bdd-4061-b723-bd3fdcfec30c)
Red is my point-cloud, and blue is sample/2 point-cloud. 

I manually applied a translation such that my point-cloud is close to the sample point-clouds and I was able to get a dexterous grasp pose now. However, the grasp pose looks weird, it d
![Screenshot from 2024-09-03 21-11-01](https://github.com/user-attachments/assets/30b5a9ca-5ab9-428d-bbe4-4cf106c66303)
oesn't seem to be able to generate a good grasp. 
![image](https://github.com/user-attachments/assets/4bcbf601-936e-48c1-8f59-d8e02272c509).

Is it because the initial hand pose relative to the object has to be in some desired orientation?

**Comment by wmtlab** [comment]
Thank you for your interest to our work. We acknowledge that there is much room for improvement in our method. Here are some suggestions:
Firstly, the input point cloud should be normalized to ensure that the position of the point cloud is consistent with the dataset.
Secondly, regarding the object you provided, I think it may be due to poor results from the first stage of generation. In this regard, our CAVE model has limited generalization performance, so you may need to retrain it.
Moreover, this optimization-based method is not always successful, which is indeed a shortcoming. You can try manually adjusting the ratios of different energies to test it.

**Comment by skymanaditya1** [comment]
Thank you for the response. How do I normalize my point clouds to be consistent with those in the dataset?

**Comment by fffffq00** [comment]
I have tested our code, and the DCoG is not affected by the translation of objects. However, the CVAE model for generating point cloud categories is sensitive to translation, which I suspect is because we did not initialize the point clouds properly during training. I apologize that I do not have enough time to retrain it at the moment. You can retrain it with a more powerful model and more appropriate data processing methods.

**Comment by skymanaditya1** [comment]
I see, I will try to get my pointclouds to align with those in your dataset and post my results here. Thanks!
